name: nutrify
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  flutter_riverpod: ^3.1.0
  riverpod_annotation: ^4.0.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  riverpod_generator: ^4.0.0+1
  freezed: ^3.2.3
  json_serializable: ^6.7.1
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
